# Generated by Django 3.2.4 on 2021-08-27 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('date', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1850, message='Please enter a year between 1850 and 2021'), django.core.validators.MaxValueValidator(2021, message='Please enter a year between 1850 and 2021')], verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='SlideshowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30, null=True, verbose_name='Headline')),
                ('bodyText', models.TextField(default='', max_length=400, verbose_name='Text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='Video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_objects.slideshow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
