# Generated by Django 3.2.4 on 2021-08-27 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_objects', '0005_alter_slideshow_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1850, message='Please enter a year between 1850 and 2021'), django.core.validators.MaxValueValidator(2060, message='Please enter a year between 1850 and 2060')], verbose_name='Year'),
        ),
    ]
