# Generated by Django 3.2.4 on 2021-08-27 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_objects', '0006_auto_20210827_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='title',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='previewPicture',
            field=models.ImageField(null=True, upload_to='', verbose_name='previewPicture'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800, message='Please enter a year between 1850 and 2100'), django.core.validators.MaxValueValidator(2100, message='Please enter a year between 1850 and 2100')], verbose_name='Year'),
        ),
    ]
