# Generated by Django 3.2.4 on 2021-08-27 17:22

import core_objects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_objects', '0008_alter_slideshow_previewpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='previewPicture',
            field=models.ImageField(null=True, upload_to='', validators=[core_objects.models.clean_picture], verbose_name='Slideshow Picture'),
        ),
        migrations.AlterField(
            model_name='slideshowitem',
            name='bodyText',
            field=models.TextField(default='', max_length=450, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='slideshowitem',
            name='headline',
            field=models.CharField(max_length=40, null=True, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='slideshowitem',
            name='image',
            field=models.ImageField(upload_to='', validators=[core_objects.models.clean_picture], verbose_name='image'),
        ),
    ]
