# Generated by Django 3.2.4 on 2021-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_objects', '0009_auto_20210827_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowitem',
            name='mediaType',
            field=models.CharField(blank=True, max_length=20, verbose_name='mediaType'),
        ),
    ]
