# Generated by Django 3.2.4 on 2021-08-27 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_objects', '0010_slideshowitem_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowitem',
            name='video',
            field=models.FileField(blank=True, null='True', upload_to='Video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
